// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (migrate, studio, db pull) use the direct connection,
    // bypassing Supabase's connection pooler. Falls back to a placeholder so
    // `prisma generate` (which needs no DB access) still works without a
    // real DIRECT_URL, e.g. in CI or a fresh Docker install.
    url: process.env.DIRECT_URL ?? "postgresql://placeholder:5432/placeholder",
  },
});
